# Uncomment the next line to define a global platform for your project

# platform :ios, '13.0'

target 'Metin2AddServerApp' do

use_frameworks!
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

end